version: '3.11.5'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: 'projectdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'