apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
        - name: flask-app-container
          image: code-app:v2.0
          ports:
            - containerPort: 5000

        - name: mysql-db-container
          image: mysql:8.0.35
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: projectdb
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: root